config-version: 1
#Make this a unique name according to your server. Preferably the same name as in velocity.
#The plugin will not boot when this is "unnamed", as this is used in some internal functions.
server-name: unnamed

#Database Details
redis-ip: "localhost"
redis-port: 6379
#For internal use, has to be a number.
redis-db: 0
#Only used if the database has auth, leave blank if not.
redis-user: ""
redis-pass: ""

#For if you want an alternative to Proton, calls Bukkit events on each instance when messages are received.
redis-use-internal-messaging: false

#SQL details